# Generated by Django 4.0.6 on 2022-10-01 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date_auth', models.DateTimeField(auto_now_add=True)),
                ('date_in', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='BackgroundPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.FloatField()),
                ('single_color', models.FloatField()),
                ('linear_gradient', models.FloatField()),
                ('radial_gradient', models.FloatField()),
                ('custom_image', models.FloatField()),
                ('select_image', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BodyViewPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.FloatField()),
                ('custom_color', models.FloatField()),
                ('custom_image', models.FloatField()),
                ('select_image', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('metadata', models.JSONField()),
                ('token_id', models.PositiveIntegerField()),
                ('avatar', models.CharField(max_length=5200000)),
                ('background', models.CharField(blank=True, max_length=5200000, null=True)),
                ('body_view', models.CharField(blank=True, max_length=5200000, null=True)),
                ('html', models.URLField()),
                ('cost', models.FloatField()),
                ('whatref', models.CharField(blank=True, max_length=8, null=True)),
                ('whatpro', models.CharField(blank=True, max_length=8, null=True)),
                ('whatamb', models.CharField(blank=True, max_length=8, null=True)),
                ('base_cost', models.FloatField()),
                ('contract', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('date_minted', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
            ],
            options={
                'verbose_name': 'config',
                'verbose_name_plural': 'configs',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('albedo', models.URLField()),
                ('normal', models.URLField()),
                ('roughness', models.URLField()),
                ('albedo_file', models.ImageField(upload_to='models/materials')),
                ('normal_file', models.ImageField(upload_to='models/materials')),
                ('roughness_file', models.ImageField(upload_to='models/materials')),
                ('displacement', models.URLField(blank=True, null=True)),
                ('displacement_file', models.ImageField(blank=True, null=True, upload_to='models/materials')),
                ('metalness', models.FloatField()),
                ('roughness_param', models.FloatField()),
                ('displacescale', models.FloatField(blank=True, null=True)),
                ('displaceshift', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
            },
        ),
        migrations.CreateModel(
            name='MintCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_sum', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='models')),
                ('link', models.URLField()),
                ('curve_radius', models.FloatField()),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'model',
                'verbose_name_plural': 'models',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.URLField(blank=True, null=True, unique=True)),
                ('percent', models.PositiveIntegerField()),
                ('isactive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'promocode',
                'verbose_name_plural': 'promocodes',
            },
        ),
        migrations.CreateModel(
            name='Returned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SelectImageBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('file', models.ImageField(upload_to='bg-img')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'std_background_image',
                'verbose_name_plural': 'std_background_images',
            },
        ),
        migrations.CreateModel(
            name='SelectImageBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('file', models.ImageField(upload_to='body-img')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'std_body_image',
                'verbose_name_plural': 'std_body_images',
            },
        ),
        migrations.CreateModel(
            name='TickerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.FloatField()),
                ('color', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SentTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('many_sol', models.FloatField()),
                ('tx', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.config')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
            ],
        ),
        migrations.CreateModel(
            name='RefferalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('paid', models.FloatField(default=0)),
                ('deals', models.PositiveIntegerField(default=0)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.config')),
            ],
            options={
                'verbose_name': 'refferal_code',
                'verbose_name_plural': 'refferal_codes',
            },
        ),
        migrations.CreateModel(
            name='ReceivedTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('many_sol', models.FloatField()),
                ('tx', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.config')),
                ('from_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
            ],
        ),
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.URLField(blank=True, null=True, unique=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
            ],
            options={
                'verbose_name': 'ambassador',
                'verbose_name_plural': 'ambassadors',
            },
        ),
    ]
