# Generated by Django 4.1.3 on 2022-12-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassador',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
