# Generated by Django 4.1.3 on 2023-06-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ambassador_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senttrans',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='senttrans',
            name='to',
        ),
        migrations.DeleteModel(
            name='ReceivedTrans',
        ),
        migrations.DeleteModel(
            name='SentTrans',
        ),
    ]
