# Generated by Django 4.2.5 on 2023-10-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_environment_font'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FontPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='environment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='font',
            name='price',
        ),
        migrations.AddField(
            model_name='environment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='font',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
