# Generated by Django 4.2.5 on 2023-10-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_envprice_fontprice_remove_environment_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='albedo_file',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='displacement_file',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='normal_file',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='roughness_file',
        ),
        migrations.RemoveField(
            model_name='models',
            name='file',
        ),
        migrations.RemoveField(
            model_name='selectimagebackground',
            name='file',
        ),
        migrations.RemoveField(
            model_name='selectimagebody',
            name='file',
        ),
        migrations.AddField(
            model_name='models',
            name='bend',
            field=models.IntegerField(default=-30),
        ),
        migrations.AddField(
            model_name='models',
            name='locX',
            field=models.IntegerField(default=-14),
        ),
        migrations.AddField(
            model_name='models',
            name='locY',
            field=models.IntegerField(default=-10),
        ),
        migrations.AddField(
            model_name='models',
            name='pozZ',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='models',
            name='shiftGlass',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='models',
            name='speed',
            field=models.IntegerField(default=15),
        ),
    ]
