# Generated by Django 4.1.3 on 2023-07-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mintactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasyMint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.URLField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Easy mint',
                'verbose_name_plural': 'Easy mints',
            },
        ),
    ]
