# Generated by Django 4.1.3 on 2023-07-19 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_easymint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refferalcode',
            options={'verbose_name': 'refferal_code', 'verbose_name_plural': 'refferal_code'},
        ),
        migrations.AlterField(
            model_name='refferalcode',
            name='config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.address'),
        ),
    ]
