# Generated by Django 4.1.3 on 2023-08-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_refferalcode_options_alter_refferalcode_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='isactive',
        ),
    ]
