# Generated by Django 4.2.5 on 2023-10-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_materials_data_alter_models_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=[{'color': '#ffffff', 'displacementMap': '', 'displacementScale': '', 'envMapIntensity': 2, 'flipY': True, 'map': 'https://arweave.net/6k2vpDLjLj5IJci_yOuU2wSWKv3FRPQ_d6gqqjWXUEQ', 'metalness': 1, 'normalMap': 'https://arweave.net/HbEPamzgLLte07Z7B0H3YzJ0vfIang6H5ijgjZI4AeM', 'roughness': 1, 'roughnessMap': 'https://arweave.net/wUqIxu-by-swZPuCg1raaYBJEr8RvCNNGGRnVf25Bh4'}, {'color': '#ffffff', 'displacementMap': '', 'displacementScale': '', 'envMapIntensity': 2, 'flipY': False, 'map': 'https://arweave.net/gRGm6t1jY9JQckEEaznTpa6YlnRl4P8140hGKdBG0lc', 'metalness': 1, 'normalMap': 'https://arweave.net/dL72U0-qz-yn4sZnhJO29F1PH84WHRI-QfY0664rV00', 'roughness': 1, 'roughnessMap': 'https://arweave.net/7UySi14E_ZTqRQlzjI9THLCE49JGw1OZT-glWyzltsQ'}, {'color': '#ffffff', 'displacementMap': '', 'displacementScale': '', 'envMapIntensity': 2, 'flipY': False, 'map': 'https://arweave.net/h54414i1wpY1e3ezqFe6xBD55HnJ-9hjAV-OvATAauM', 'metalness': 1, 'normalMap': 'https://arweave.net/wNg7XexkW-EZCLQB2XUi9Lzousa2yd5hjV8pH-bZBT4', 'roughness': 1, 'roughnessMap': 'https://arweave.net/uFQL34uuYCBIOkB-SWYldLcuijEBcyVz5R1nqyQBoeo'}])),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
    ]
