# Generated by Django 4.1.3 on 2023-08-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_promocode_isactive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambassador',
            options={'verbose_name': '2ambassador', 'verbose_name_plural': '2ambassadors'},
        ),
        migrations.AlterModelOptions(
            name='easymint',
            options={'verbose_name': '4Easy mint', 'verbose_name_plural': '4Easy mints'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': '3promocode', 'verbose_name_plural': '3promocodes'},
        ),
        migrations.AlterModelOptions(
            name='refferalcode',
            options={'verbose_name': '1refferal_code', 'verbose_name_plural': '1refferal_code'},
        ),
    ]
