# Generated by Django 4.2.5 on 2023-10-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hat',
            options={'verbose_name': 'Hat', 'verbose_name_plural': 'Hats'},
        ),
    ]
